# Generated by Django 3.2 on 2021-04-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionDataForSale',
        ),
    ]
