# Generated by Django 3.1.7 on 2021-03-31 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.AddField(
            model_name='deals',
            name='ReceveEmail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='days',
            field=models.CharField(choices=[('mon,tue,wed,thu,fri,sat,sun', 'Daily'), ('sat,sun', 'Weekends')], default='Daily', max_length=100),
        ),
        migrations.AddField(
            model_name='deals',
            name='time',
            field=models.IntegerField(blank=True, choices=[(5, '5:00am'), (6, '6:00am'), (7, '7:00am'), (8, '8:00am'), (17, '5:00pm'), (21, '9:00pm'), (22, '10:00pm')], null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adress',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='assettypes',
            name='limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='computedeals',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, '1 month'), (3, '3 months'), (6, '6 months'), (12, 'One year')], null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionDataForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('listing_id', models.IntegerField(blank=True, null=True)),
                ('products', models.CharField(blank=True, max_length=1000, null=True)),
                ('rdc_web_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('prop_type', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('branding', models.JSONField(blank=True, null=True)),
                ('prop_status', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('baths_full', models.IntegerField(blank=True, null=True)),
                ('baths', models.IntegerField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('building_size', models.JSONField(blank=True, null=True)),
                ('agents', models.JSONField(blank=True, null=True)),
                ('office', models.JSONField(blank=True, null=True)),
                ('last_update', models.CharField(blank=True, max_length=1000, null=True)),
                ('client_display_flags', models.JSONField(blank=True, null=True)),
                ('lead_forms', models.JSONField(blank=True, null=True)),
                ('photo_count', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=1000, null=True)),
                ('page_no', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('list_tracking', models.CharField(blank=True, max_length=1000, null=True)),
                ('lot_size', models.JSONField(blank=True, null=True)),
                ('mls', models.JSONField(blank=True, null=True)),
                ('data_source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('baths_half', models.FloatField(blank=True, null=True)),
                ('virtual_tour', models.CharField(blank=True, max_length=1000, null=True)),
                ('prop_sub_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('open_houses', models.CharField(blank=True, max_length=1000, null=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.deals')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('listing_id', models.IntegerField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('client_display_flags', models.JSONField(blank=True, null=True)),
                ('products', models.CharField(blank=True, max_length=1000, null=True)),
                ('agents', models.CharField(blank=True, max_length=1000, null=True)),
                ('lead_forms', models.JSONField(blank=True, null=True)),
                ('building_size', models.JSONField(blank=True, null=True)),
                ('rdc_app_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('data_source_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
                ('page_no', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('list_tracking', models.CharField(blank=True, max_length=1000, null=True)),
                ('photo_count', models.IntegerField(blank=True, null=True)),
                ('prop_type', models.CharField(blank=True, max_length=20, null=True)),
                ('list_date', models.CharField(blank=True, max_length=20, null=True)),
                ('last_update', models.CharField(blank=True, max_length=20, null=True)),
                ('year_built', models.FloatField(blank=True, null=True)),
                ('listing_status', models.CharField(blank=True, max_length=20, null=True)),
                ('prop_status', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('lot_size', models.JSONField(blank=True, null=True)),
                ('rdc_web_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('community', models.JSONField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.deals')),
            ],
        ),
    ]
