# Generated by Django 3.2 on 2021-04-20 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_address', to='deal.deals'),
        ),
        migrations.AlterField(
            model_name='assetsforrent',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_assets_for_rent', to='deal.deals'),
        ),
        migrations.AlterField(
            model_name='assetsforsale',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_assets_for_sale', to='deal.deals'),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforrent',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_subscription_for_rent', to='deal.deals'),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_subscription_for_sale', to='deal.deals'),
        ),
    ]
