# Generated by Django 3.1.7 on 2021-03-31 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_auto_20210331_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deal.deals'),
        ),
    ]
