# Generated by Django 3.2 on 2021-04-29 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0002_delete_subscriptiondataforsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDataForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_photo', models.JSONField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.JSONField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('permalink', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('list_date', models.DateTimeField(blank=True, null=True)),
                ('open_houses', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.JSONField(blank=True, null=True)),
                ('branding', models.JSONField(blank=True, null=True)),
                ('list_price', models.IntegerField(blank=True, null=True)),
                ('lead_attributes', models.JSONField(blank=True, null=True)),
                ('property_id', models.CharField(blank=True, max_length=255, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('flags', models.JSONField(blank=True, null=True)),
                ('community', models.CharField(blank=True, max_length=50, null=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('virtual_tours', models.CharField(blank=True, max_length=50, null=True)),
                ('other_listings', models.JSONField(blank=True, null=True)),
                ('listing_id', models.CharField(blank=True, max_length=50, null=True)),
                ('price_reduced_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('matterport', models.CharField(blank=True, max_length=10, null=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_subscription_for_sale', to='deal.deals')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
