# Generated by Django 3.2 on 2021-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20210411_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assetsforrent',
            name='cats_ok',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='assetsforrent',
            name='dogs_ok',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
