# Generated by Django 3.2 on 2021-04-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_subscriptiondataforsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='branding',
            field=models.JSONField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='description',
            field=models.JSONField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='flags',
            field=models.JSONField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='lead_attributes',
            field=models.JSONField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='location',
            field=models.JSONField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='other_listings',
            field=models.JSONField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='photos',
            field=models.JSONField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='primary_photo',
            field=models.JSONField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='products',
            field=models.JSONField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='source',
            field=models.JSONField(blank=True, max_length=100000, null=True),
        ),
    ]
