# Generated by Django 3.2 on 2021-04-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_auto_20210429_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='branding',
            field=models.JSONField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='community',
            field=models.CharField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='description',
            field=models.JSONField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='flags',
            field=models.JSONField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='lead_attributes',
            field=models.JSONField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='listing_id',
            field=models.CharField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='location',
            field=models.JSONField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='matterport',
            field=models.CharField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='open_houses',
            field=models.CharField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='permalink',
            field=models.CharField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='photos',
            field=models.JSONField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='price_reduced_amount',
            field=models.CharField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='primary_photo',
            field=models.JSONField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='products',
            field=models.JSONField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='property_id',
            field=models.CharField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='source',
            field=models.JSONField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='status',
            field=models.CharField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='tags',
            field=models.CharField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondataforsale',
            name='virtual_tours',
            field=models.CharField(blank=True, max_length=10485760, null=True),
        ),
    ]
