api_key="aecb438fd4mshcbfaff7d555143bp109ee0jsn81774e92b1a4"
host = "us-real-estate.p.rapidapi.com"
url_for_sale = "https://us-real-estate.p.rapidapi.com/for-sale"
url_for_rent = "https://us-real-estate.p.rapidapi.com/for-rent"
url_estimate = "https://us-real-estate.p.rapidapi.com/for-sale/home-estimate-value"