name: Testing
on: push


jobs:
  test_project:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: WhiteCow Unit test
      run: |
        python3 -m pip install --upgrade pipenv wheel
        pip3 install --user celery, coverage,django,six,django-crispy-forms,django-heroku,pandas,selenium,unittest-xml-reporting,junit2html
        python3 manage.py test

