name: Testing
on: push


jobs:
  test_project:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: WhiteCow Unit test
      run: |
        pip3 install --user pipenv
       
        pipenv install --user
        python3 manage.py test

