name: Testing
on: push


jobs:
  test_project:
    runs-on: macos-latest

    services:
      db_service:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: whitecowdb
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: WhiteCow Unit test
      run: |
        python3 -m pip install --upgrade pipenv wheel
        pip3 install --user celery
        pip3 install --user coverage
        pip3 install --user django-crispy-forms
        pip3 install --user six
        pip3 install --user django
        pip3 install --user django-heroku
        pip3 install --user pandas
        pip3 install --user selenium
        pip3 install --user unittest-xml-reporting
        pip3 install --user junit2html
        pip3 install --user django-nose
        pip3 install --user whitenoise
        pip3 install --user django-celery-beat
        pip3 install --user django-enum-choices
        pip3 install --user django-bootstrap-modal-forms
        pip3 install --user redis
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 manage.py test

