name: Testing
on: push


jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WhiteCow Unit test
      run: |
        pip3 install --user pipenv
        pipenv shell
        pipenv install
        python3 manage.py test

