name: Testing
on: push


jobs:
  test_project:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: WhiteCow Unit test
      run: |
        python3 -m pip install --upgrade pipenv wheel
        pipenv install
        python3 manage.py test

