name: Testing
on: push


jobs:
  test_project:
    runs-on: macos-latest
    steps:
    - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

    - uses: actions/checkout@v2
    - name: WhiteCow Unit test
      run: |
        
        pipenv shell
        pipenv install 
        python3 manage.py test

